

@scheme = https
@ades = test.eodatahub.org.uk/ades
@username=sparkgeouser
@workspace = sparkgeouser

@executeStatus = {{executeProcess.response.headers.Location}}


@processName = lst



###

# @name use_fastapi

POST {{base_url}}/get-data-values/
Accept: application/json
Content-Type: application/json
Connection: keep-alive

< /Users/sgdowd/Documents/1_EODH/values_from_cogs2/docs/api_input_nostac.json


###
# @name call_lambda
POST {{base_url}}values
Accept: application/json
Content-Type: application/json

< /Users/sgdowd/Downloads/locon_schools_simple_no_comma_unix.geojson

###

# @name executeProcess
POST https://test.eodatahub.org.uk/ades/{{workspace}}/ogc-api/processes/{{processName}}/execution HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

< workflow_input_s3.json

###

# @name getExecuteStatus
GET {{executeStatus}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


# @name getResults
GET https://{{workspace}}.workspaces.test.eodhp.eco-ke-staging.com/files/eodhp-test-workspaces1/processing-results/cat_{{getExecuteStatus.response.body.jobID}}.json HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json