

@scheme = https
@ades = test.eodatahub.org.uk/ades
@username=sparkgeouser
@workspace = sparkgeouser

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

@jobid = {{getExecuteStatus.response.body.jobID}}

@processName = lst2




###

# @name listProcesses
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/{{processName}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "executionUnit": {
    "href": "https://eodh-cwl.s3.eu-west-1.amazonaws.com/get_asset_values.cwl",
    "type": "application/cwl"
  }
}

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/{{processName}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
