

@scheme = https
@ades = test.eodatahub.org.uk/ades
@username=sparkgeouser
@workspace = sparkgeouser

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

@jobid = {{getExecuteStatus.response.body.jobID}}

@processName = get-asset-values-workflow-nostac




###

# @name listProcesses
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/{{processName}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "executionUnit": {
    "href": "https://gist.githubusercontent.com/geodowd/1776c94ac067989a1222e457c023abb9/raw/c35110db6badd4fbec2dd52cb3ffe5828a9249ae/value_2_0_1.cwl",
    "type": "application/cwl"
  }
}

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/{{processName}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
